[package]
name = "greedy"
version = "0.1.0"
edition = "2024"

[dependencies]
icfpc2025-client = { path = "../client" }
tokio = { workspace = true }
dotenvy = { workspace = true }
anyhow = { workspace = true }
rand = "0.9.2"

[[bin]]
name = "greedy"
path = "src/main.rs"
